### PR TITLE
Fix for #457 (AbstractAccessControlProvider.checkForCyclicDependencies buggy)

### LINKED ISSUE #457: AbstractAccessControlProvider.checkForCyclicDependencies buggy
https://github.com/oasp/oasp4j/blob/develop/modules/security/src/main/java/io/oasp/module/security/common/base/accesscontrol/AbstractAccessControlProvider.java#L68

If two groups inherit from the same parent group the code detects a cycle and raises an error. This is actually wrong. We need to fix asap.

### PR DESCRIPTION
**Pull request by hohwille**
I fixed #457 and hope you like it :)

### CODE REVIEW

**Comment by hohwille** [comment]
Seems as travis got stuck in a download of some useless `maven-metadata.xml`.

File: modules/security/src/main/java/io/oasp/module/security/common/api/accesscontrol/AccessControlGroup.java [hunk 1]
```diff
@@ -141,20 +135,11 @@ public boolean equals(Object obj) {
     if (!super.equals(obj)) {
       return false;
     }
-    if (getClass() != obj.getClass()) {
-      return false;
-    }
     AccessControlGroup other = (AccessControlGroup) obj;
```
Comment (maybeec) [inline modules/security/src/main/java/io/oasp/module/security/common/api/accesscontrol/AccessControlGroup.java]: you introduced a potential `ClassCastException` here.

File: modules/security/src/main/java/io/oasp/module/security/common/base/accesscontrol/AbstractAccessControlProvider.java [hunk 2]
```diff
@@ -63,17 +67,19 @@ protected void initialize(AccessControlSchema config) {
...
+  protected void checkForCyclicDependencies(AccessControlGroup group, NodeCycle<AccessControlGroup> nodeCycle) {
 
-    boolean added = visitedGroups.add(group);
-    if (!added) {
-      // mmm NodeCycleException would be very helpful here...
-      throw new IllegalStateException("Cyclic inheritance of access control groups detected for " + group);
-    }
     for (AccessControlGroup inheritedGroup : group.getInherits()) {
-      checkForCyclicDependencies(inheritedGroup, visitedGroups);
+      List<AccessControlGroup> inverseCycle = nodeCycle.getInverseCycle();
```
Comment (maybeec) [inline modules/security/src/main/java/io/oasp/module/security/common/base/accesscontrol/AbstractAccessControlProvider.java]: It is not clear for me why you need this NodeCycle stuff. The class claimed, that it is a datastructure to detect cycles. However, you are just simulating a stack here, It is somehow confusing to work with a "cycle" here, which does not represent a cycle at all. In addition to that, inverseCycle is even more strange especially as the javaDoc of this function does not state what the return value of this method will be if there is no cycle. 
Is it simply the exception to be reused here?

Maybe `visitedGroups` is not the correct name anymore, but `nodeCycle` neither. It does not has anything in common with the value of the parameter. More suitable would be visitedStack or something like this.

File: modules/security/src/main/java/io/oasp/module/security/common/api/accesscontrol/AccessControlGroup.java (hunk 1 above)
Comment (hohwille) [inline modules/security/src/main/java/io/oasp/module/security/common/api/accesscontrol/AccessControlGroup.java]: Wrong. ```AccessControlGroup``` extends ```AccessControl``` that already contains the same check in ```equals```. As ```super.equals(obj)``` has to be true at this point the if check was redundant and pointless here.

File: modules/security/src/main/java/io/oasp/module/security/common/base/accesscontrol/AbstractAccessControlProvider.java (hunk 2 above)
Comment (hohwille) [inline modules/security/src/main/java/io/oasp/module/security/common/base/accesscontrol/AbstractAccessControlProvider.java]: I am fine with your suggestion as long as you provide an update or patch with that change. I am just reusing code that solves exactly what we need to have here. If you use ```java.util.Stack``` you will IMHO have to write more code and documentation around and would more or less duplicate the reused solution. However, I do not care and I seem to be biased according to mmm usage.

File: modules/security/src/main/java/io/oasp/module/security/common/api/accesscontrol/AccessControlGroup.java (hunk 1 above)
Comment (jomora) [inline modules/security/src/main/java/io/oasp/module/security/common/api/accesscontrol/AccessControlGroup.java]: The `super.equals(...)` method will perform an additional `this == obj` check, but it will also check for `null` and for `class` equality - and in addition the super class' properties (here `id`) will be checked. Therefore, this shortens the code of `AccessControlGroup.equals(...)`.

Regarding the `ClassCastException` a short test method will show that there is no problem:
```java
  @Test
  public void testSuperClassType() {

    // setup
    AccessControlGroup acg = new AccessControlGroup();
    AccessControl ac = new MyAccessControl();

    // verify
    assertThat(acg.equals(ac)).isEqualTo(false);
    assertThat(ac.equals(acg)).isEqualTo(false);
  }
```

From my point of view this should be considered correct.

File: modules/security/src/main/java/io/oasp/module/security/common/base/accesscontrol/AbstractAccessControlProvider.java (hunk 2 above)
Comment (jomora) [inline modules/security/src/main/java/io/oasp/module/security/common/base/accesscontrol/AbstractAccessControlProvider.java]: @maybeec just to clarify: you propose a renaming of `visitedGroups` to (for example) `vistiedStack`?

Comment (maybeec) [inline modules/security/src/main/java/io/oasp/module/security/common/base/accesscontrol/AbstractAccessControlProvider.java]: No, just wondering about the solution. But I am fine with it as long as it fits the intended behavior.

**Comment by jomora** [comment]
Since all problems have been addressed in the discussion, I merged the PR.
